config/routes.rb
Rails.application.routes.draw do

  match '/404', :to => 'errors#not_found', :via => :all

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }

  devise_scope :user do
    controller 'users/sessions' do
      get ':alias/sign_in' => :new, as: :new_brand_session
      post ':alias/sign_in' => :create, as: :brand_session
      root action: :new
    end
  end

  get '/dashboard', to: 'dashboard#index'
  resources :brands do
    resources :users, controller: 'brand_users' do
      member do
        get :activity
        get :diagnostic
      end
    end
    resources :startups, path_names: { new: 'push' }, controller: :brand_startups,
              only: [:index, :new, :create, :destroy] do
      get :delete, on: :member
    end
    member do
      patch :update_question
      delete :delete_question
      get :brief
      get :modify
      get :promo_pages
      get :settings
      controller :brands do
        patch 'refresh' => :refresh_persisted
      end
      get :delete
    end
    collection do
      post :create_question
      post 'refresh' => 'brands#refresh'
      get :search
    end
  end

  resources :email_templates
  resources :brand_questions
  resources :announcements
  post '/announcements/upload', to: 'announcements#upload_image',
                                as: :announcements_upload_image
  resources :users do
    member do
      post :reset_password
      get  :activity
      get  :diagnostic
    end
  end

  resources :activities do
    collection do
      get :requests
      get :updates
      get :my_tasks
      get :assigned_tasks
    end
  end

  resources :invites do
    get :new_startup, on: :collection
    get :delete, on: :member
  end

  resources :startups, path_names: { notes: 'comments' } do
    resources :announcements, controller: 'startup_announcements', only: [:index, :show]
    resources :tags, controller: :startup_tags, only: [:index, :create, :destroy]
    post :add_pdf
    delete 'destroy_pdf/:pdf_id' => 'startups#destroy_pdf', as: :destroy_pdf
    member do
      get :tags
      get :profile
      get :questions
      get :notes
      get :tasks
      get :home
      get :requests
      get :all_questions
      get :activity
      get :cabinet
      controller :startups do
        get 'push' => :new_push
        post 'push' => :create_push
        get 'add_to_list' => :new_add_to_list
        post 'add_to_list' => :create_add_to_list
      end
      get   :edit_watchlist
      patch :update_watchlist
      get   :delete
    end
    collection do
      put :cancel
      get :search
      get :watchlist
      post '/download/:type', to: 'startups#download', as: 'download'
    end
    resources :brief, controller: :startup_brief_summaries do
      get :to_step, on: :collection
    end
    resources :profile_questions, except: :destroy
  end

  resources :startup_brief_summaries

  resources :search do
    collection do
      post :quick
      get :quick
      get :saved
      get :advanced
      post :adv
      get :by_categories
      get 'adv', to: 'search#adv_filter'
      resources :tags, except: [:edit, :update] do
        collection do
          delete :delete_tag
        end
      end
    end
    member do
      get :edit_name
      patch :update_name
    end
  end

  resources :lists do
    get :remove_from, on: :member
    collection do
      get :search
      get :add_to_favorites
      get :remove_from_favorites
    end
  end
  put 'sort_lists', to: 'lists#sort', as: :sort_lists
  put 'reset_list_sorting', to: 'lists#reset_sorting', as: :reset_list_sorting

  resources :requests do
    get :seen, on: :member
  end
  resources :notes do
    resources :comments, controller: :note_comments, only: [:edit, :create, :update, :destroy]
    member do
      get :delete
      get :mark_as_done
      get :mark_as_undone
    end
  end

  resources :brand_brief_summaries
  resources :user_diagnostic_summaries

  scope 'settings' do
    get 'diagnostic', to: 'diagnostic#index'
    resources :diagnostic_questions
    resources :diagnostic_types, only: [:index, :edit, :update]
    resources :packages do
      get :delete, on: :member
    end
    resources :brand_brief do
      member do
        get :modify
      end
    end
    resources :promo_pages, except: [:show] do
      member do
        patch :update_question
        delete :delete_question
        get 'unpublish' => 'promo_pages#new_unpublish'
        patch :unpublish
        patch :reject
        patch :approve
        patch 'refresh' => 'promo_pages#refresh_persisted'
        get :view_questions
        get :preview
      end
      collection do
        post :create_question
        post 'refresh' => 'promo_pages#refresh'
        get :brand_questions
      end
    end
  end

  get '/promo/:alias', to: 'promo_pages#show', as: :promo

  scope path: '/startup_brand_brief', controller: :startup_brand_briefs do
    get ':brand_alias' => :new, as: :new_startup_brand_brief
    post ':brand_alias' => :create, as: :startup_brand_brief
  end

  scope path: '/startup_promo_brief', controller: :startup_promo_briefs do
    get ':promo_alias' => :new, as: :new_startup_promo_brief
    post ':promo_alias' => :create, as: :startup_promo_brief
  end


  resources :scorecards do
    collection do
      get 'show_by_token/:token' => 'scorecards#show_by_token', as: :show_by_token
      get 'cancel'
      post 'refresh'
      patch 'refresh_persisted'
      get 'download_list/:template_id' => 'scorecards#download_list', as: :download_list
      post 'generate_pdf' => 'scorecards#generate_pdf', as: :generate_pdf
      get 'search_startups'
    end
    patch 'push'
  end
  resources :scorecard_templates do
    get 'generate_xls'
    collection do
      patch 'refresh_persisted'
      post 'add_question'
      get 'cancel'
      post 'refresh'
    end
  end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  enum send_to: [:all_u, :startup_u, :brand_u, :selected_u]
  paginates_per 5

  belongs_to  :creator, class_name: 'User', foreign_key: :creator_id, unscoped: true
  has_many    :announcement_receivers
  has_many    :startups, through: :announcement_receivers
  has_many    :brands, through: :announcement_receivers

  validates :title, :content, presence: true
  validates :receiver_ids, presence: true, if: :sent_to_user?

  mount_uploader :cover, AnnouncementPictureUploader

  after_create :save_recievers

  attr_accessor :receiver_ids

  scope :user_announcement, -> (user) do
    if user.evo_team?
      includes(:creator, :announcement_receivers, :startups, :brands)
          .order(created_at: :desc)
    elsif user.startup?
      joins(:announcement_receivers)
          .where(announcement_receivers: { receiver_type: 0, receiver_id:  user.startup.id })
          .includes(:creator).order(created_at: :desc)
    else
      joins(:announcement_receivers)
          .where(announcement_receivers: { receiver_type: 1, receiver_id: user.brand.id })
          .includes(:creator).order(created_at: :desc)
    end
  end

  scope :get_announcement, -> (user, id) do
    if user.evo_team?
      includes(:startups, :brands).where(id: id).first
    elsif user.startup?
      joins(:announcement_receivers)
          .where(announcement_receivers: {
                 receiver_type: 0,
                 receiver_id:  user.startup.id }, id: id).first
    else
      joins(:announcement_receivers)
          .where(announcement_receivers: {
                 receiver_type: 1,
                 receiver_id:  user.brand.id }, id: id).first
    end
  end

  scope :undelivered, -> { where(delivered: nil) }

  def find_receivers
    @startups = []
    @brands = []
    case send_to
      when 'all_u'
        # @startups = Startup.where.not(owner_id: nil)
        @brands = Brand.all.includes(:users)
      when 'startup_u'
        @startups = Startup.where.not(owner_id: nil)
      when 'brand_u'
        @brands = Brand.all.includes(:users)
    end
    save_reciver_details
  end

  protected

  def sent_to_user?
    self.selected_u?
  end

  def save_recievers
    if sent_to_user?
      startup = []
      brand = []
      receiver_ids.each do |receiver|
        t, id = receiver.split('=')
        if t == '0'
          startup << id.to_i
        else
          brand << id.to_i
        end
      end
      @startups = Startup.where(id: startup).includes(:owner)
      @brands = Brand.where(id: brand).includes(:users)
      save_reciver_details
    end
  end

  def save_reciver_details
    # @startups.each do |startup|
    #   AnnouncementReceiver.create(
    #       announcement_id: self.id,
    #       receiver_type: 0,
    #       receiver_id: startup.id,
    #       user_ids: [startup.owner_id]
    #   )
    # end
    @brands.each do |brand|
      if brand.users.any?
        AnnouncementReceiver.create(
            announcement_id: self.id,
            receiver_type: 1,
            receiver_id: brand.id,
            user_ids: brand.users.pluck(:id)
        )
      end
    end
    self.update_column(:delivered, true)
    sending_announcement_activity
  end

  def sending_announcement_activity
    user = self.creator
    receivers_array = @startups.pluck(:title) + @brands.pluck(:title)
    receivers = scrape_receivers(receivers_array)
    brand_activities = []
    activity = Activity.find_by(alias: 'm_mv_post_was_sent')

    evo_text = Activity.prepare_texts(patterns: { evo: activity[:evo_pattern] },
                                      replaces: ['{{user_name}}', '{{post_name}}', '{{users}}'],
                                      replacements: [user.full_name, self.title, receivers])
    brand_text = Activity.prepare_texts(patterns: { brand: activity[:brand_pattern] },
                                        replaces: ['{{post_name}}'],
                                        replacements: [self.title])
    evo_activity = [UserActivity.new(user: user, activity: activity, evo_text: evo_text[:evo])]
    @brands.each do |brand|
      brand_activities << UserActivity.new(user: user, activity: activity, 
                                           brand_text: brand_text[:brand],
                                           resource_type: :brand,
                                           resource_id: brand.id,
                                           evo_logo: true)
    end
    activities = brand_activities + evo_activity
    UserActivity.import activities
    sending_emails_about_activities
  end

  def sending_emails_about_activities
    BrandMailer.announcement_received(@brands, self).deliver_now
    StartupMailer.announcement_received(@startups, self).deliver_now
  end

  def scrape_receivers(users)
    case
    when all_u?
      'All Users'
    when brand_u?
      'All Brands'
    when startup_u?
      'All Startups'
    else
      users.join(', ')
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  load_and_authorize_resource
  before_action :startup_brand_users, only: [:new, :create]
  before_action :redirect_startup_user, only: [:show]

  def index
    @announcements = Announcement.user_announcement(current_user).page(params[:page])
  end

  def show
    @announcement = Announcement.get_announcement(current_user, params[:id])
  end

  def new
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.new(announcement_params)
    if params[:type] == 'create'
      if @announcement.save
        flash.now[:notice] = { title: 'Done',
                               text: 'Announcement was successfully sent.' }
      else
        flash.now[:notice] = { title: 'Done',
                               text: 'Announcement send error.'}
      end
      render 'create'
    else
      render 'preview'
    end
  end

  def upload_image
    image = AnnouncementImage.create(image: params[:file])
    if image.save
      render json: { link: image.image.url }
    else
      render json: { error: 'failed to save image' }, status: 500
    end
  end

  private

  def redirect_startup_user
    redirect_to startup_announcements_path(current_user.startup) if current_user.startup?
  end

  def announcement_params
    params.require(:announcement).permit(
        :title,
        :send_to,
        :content,
        :cover,
        :cover_cache,
        receiver_ids: []
    ).merge(creator_id: current_user.id)
  end

  def startup_brand_users
    startups = []
    brands = []
    if params[:announcement] && params[:announcement][:receiver_ids]
      params[:announcement][:receiver_ids].each do |receiver|
        t, id = receiver.split('=')
        if t == '0'
          startups << id.to_i
        else
          brands << id.to_i
        end
      end
    end
    @choices = []
    @choices[0] = []
    @choices[1] = []
    # Startup.where.not(owner_id: nil).each do |startup|
    #   s = {
    #       id: startup.id,
    #       title: startup.title,
    #       logo: startup.logo? ? startup.logo.thumb_small : 's_img.png',
    #       selected: startups.include?(startup.id)
    #   }
    #   @choices[0] << s
    # end
    Brand.all.each do |brand|
      b = {
          id: brand.id,
          title: brand.title,
          logo: brand.logo? ? brand.logo.thumb_small : 'b_img.png',
          selected: brands.include?(brand.id)
      }
      @choices[1] << b
    end
  end


end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def announcement_users_text(announcement)
    case
    when announcement.all_u?
      'All Users'
    when announcement.brand_u?
      'All Brands'
    when announcement.startup_u?
      'All Startups'
    end
  end
end

app/views/announcements/_announcement.html.erb
<%= link_to announcement_path(announcement.id), remote: true, class: 'section_item btn_open_panel' do %>
  <%= render 'blank_list_item', announcement: announcement %>
  <% if announcement.cover? %>
    <span class="section_img" style="background-image: url(<%= announcement.cover.url%>);">
    </span>
  <% end %>
  <span class="section_content">
    <h4 class="section_title">
      <%= announcement.title %>
    </h4>
    <span class="section_date">
      <span class="section_by visible-xs-inline-block">by <%= announcement.creator.full_name %> <span>|</span></span> <%= announcement.created_at.strftime('%b %-d, %Y') %>
    </span>
    <span class="section_text ellipsis_text">
      <%= strip_tags(announcement.content) %>
    </span>
    <% if current_user.evo_team? %>
      <span class="list_logo clearfix">
        <% if announcement.selected_u? %>
          <% counter = 0 %>
          <% announcement.announcement_receivers.each_with_index do |receiver, i| %>
            <span href="#" class="list_logo_item <%= i > 5 ? 'hidden' : ''%>">
              <% if receiver.receiver_type %>
                <% if receiver.brand.logo? %>
                  <%= image_tag receiver.brand.logo.thumb_small, alt: '', title: receiver.brand.title %>
                <% else %>
                  <%= receiver.brand.initial %>
                <% end %>
              <% else %>
                <% if receiver.startup.logo? %>
                  <%= image_tag receiver.startup.logo.thumb_small, alt: '', title: receiver.startup.title %>
                <% else %>
                  <%= receiver.startup.initial %>
                <% end %>
              <% end %>
            </span>
            <% counter += 1 if i > 5 %>
          <% end %>
          <% if counter > 0 %>
            <span href="#" class="list_logo_item">
              <span>+ <%= counter %></span>
            </span>
          <% end %>
        <% else %>
          <%= announcement_users_text(announcement) %>
        <% end %>
      </span>
    <% end %>
  </span>
<% end %>

app/views/announcements/_blank_list_item.html.erb
<span class="section_item placeholder_styles">
  <% if announcement.cover? %>
    <span class="section_img"></span>
  <% end %>
  <span class="section_content">
    <h4 class="section_title"></h4>
    <span class="section_date">
      <span class="section_by visible-xs-inline-block"></span>
    </span>
    <span class="section_text ellipsis_text">
      <span class="placeholder_line_text" style="width: 95%"></span>
    </span>
    <% if current_user.evo_team? %>
    <span class="list_logo clearfix">
      <span class="list_logo_item"></span>
      <span class="list_logo_item"></span>
      <span class="list_logo_item"></span>
      <span class="list_logo_item"></span>
      <span class="list_logo_item"></span>
    </span>
    <% end %>
  </span>
</span>

app/views/announcements/_empty_announcement.html.erb
<div id="empty-announcement" class="empty_block empty_block_pt">
  <div class="text-right hidden-xs btn_right_block">
    <% if can? :create, Announcement %>
      <%= link_to '+ Send Announcement', new_announcement_path, remote: true, class: 'btn btn_add btn_in_empty absolute', data: { panel: 'send_announcement' } %>
    <% end %>
  </div>
  <i class="icon icon_page"></i>
  <h1 class="empty_title"><span class="empty_title_inner">Madison + Mountain View</span></h1>
  <p class="empty_text">Insights from the world of startups and brands</p>
</div>

app/views/announcements/_form.html.erb
<h1 class="h1_title">Create Post</h1>
<div class="subtitle">You will be able to send the post to all users, specific users or a single user.</div>
<%= form_for @announcement, remote: true, html: {} do |f| %>
  <div class="grid_padding_sm form_container">
    <%= hidden_field_tag 'type', 'create' %>
    <div class="form-group">
      <%= f.text_field :title, placeholder: 'Enter Title', class: 'form-control' %>
    </div>

    <div class="check_list check_list_changed">
      <div class="check_list_name">SEND TO</div>
      <div class="btn-group btn_check_group clearfix" data-toggle="buttons">
        <!--<label class="btn btn_input_simple active">-->
          <% f.radio_button :send_to, "all_u", checked: true, class: 'send-to', autocomplete: 'off' %><!--<span>All Users</span>-->
        <!--</label>-->
        <!--<label class="btn btn_input_simple">-->
          <% f.radio_button :send_to, "startup_u", class: 'send-to', autocomplete: 'off' %><!--<span>Only Startups</span>-->
        <!--</label>-->
        <label class="btn btn_input_simple">
          <%= f.radio_button :send_to, "brand_u", class: 'send-to', autocomplete: 'off' %> <span>All Brands</span>
        </label>
        <label class="btn btn_input_simple">
          <%= f.radio_button :send_to, "selected_u", class: 'send-to', autocomplete: 'off' %> <span>Selected Brands</span>
        </label>
      </div>
    </div>

    <div class="hidden_selected_users clearfix">
      <div class="multiple_tag_select">
        <div class="error_field">
          <select name="announcement[receiver_ids][]" id="receiver_ids" multiple="multiple" class="js-example-basic-multiple" data-placeholder="Start typing brand name">
            <% @choices.each_with_index do |collection, i| %>
              <% collection.each do |receiver| %>
                <%= content_tag(:option, receiver[:title], value: "#{i}=#{receiver[:id]}", 'data-img-src' => asset_path(receiver[:logo]), selected: (receiver[:selected] ? 'selected' : receiver[:selected])) %>
              <% end %>
            <% end %>
          </select>
          <% if @announcement.errors && @announcement.errors.messages[:receiver_ids] %>
            <span class="error_text"><%= @announcement.errors.messages[:receiver_ids].first %></span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="editor_holder">
      <div class="form-group">
        <label>ANNOUNCEMENT TEXT</label>
        <%= f.text_area(:content, placeholder: 'Type something', class: 'announcemtn-text-edtior') %>
      </div>
    </div>

    <div class="invers_btns left">
      <a href="#" class="btn btn_add btn_file">Upload Cover
        <%= f.file_field :cover, class: 'file_upload_cover' %>
        <%= f.hidden_field :cover_cache %>
      </a>
      <a href="#" class="btn btn_bordered_const md_size btn_remove_file_name">Cancel</a>
      <div class="selected_file_name"><%= @announcement.cover %></div>
    </div>
  </div>

  <div class="bot_control_btns">
    <div class="row">
      <div class="col-xs-12 text-center">
        <a href="#" class="control_link dismiss_one_panel">CANCEL</a>
        <a href="#" class="control_link btn_open_panel" id='show-preview'>PREVIEW</a>
        <a id="send-announcement" href="#" class="control_link dismiss_panels btn_call_notification btn_show_mark btn_loader">
          <span>SEND</span><i class="icon icon_mark"></i>
          <%= render '/layouts/loader' %>
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/announcements/_index.html.erb
<div class="mmv_holder">
  <% if can? :create, Announcement %>
    <div class="text-right hidden-xs btn_right_block">
      <%= link_to '+ Send Announcement', new_announcement_path, remote: true, class: 'btn btn_add btn_open_panel', data: { panel: 'send_announcement' } %>
    </div>
  <% end %>
  <h2 class="mobile_title visible-xs">M+MV</h2>
  <div class="head_content head_content_padd hidden-xs">
    <h1 class="h1_title">Madison Ave + Mountain View</h1>
    <div class="subtitle">Content curated by the Evol8tion team.</div>
  </div>
  <div id="announcement-list">
    <% unless @announcements.nil? %>
      <%= render @announcements %>
    <% end %>
  </div>
</div>

app/views/announcements/_new.html.erb
<%= render partial: 'form' %>

app/views/announcements/_show.html.erb
<div class="slide-panel_header">
  <div class="slide-panel_header_bg" style="background-image: url(<%= @announcement.cover ? @announcement.cover.url : '' %>);"></div>
  <% unless defined?(dont_show_exit) %>
    <a id='announcement-hide-panel' href="#" class="link_nav"><i class="icon icon_close"></i></a>
  <% end %>
  <h2 class="slide-panel_title"><%= @announcement.title %></h2>
  <div class="slide-panel_subtitle">
    <span>sent: </span>
    <% if @announcement.created_at? %>
      <%= @announcement.created_at.strftime('%m/%e/%Y') %>
    <% else %>
      <%= Time.now.strftime('%m/%e/%Y') %>
    <% end %>
  </div>
</div>
<div class="slide-panel_body">
  <% if current_user.evo_team? && @announcement.announcement_receivers.any? %>
    <div class="list_logo list_logo_padd clearfix">
      <span class="list_logo_text">TO:</span>
      <% if @announcement.selected_u? %>
        <% counter = 0 %>
        <% @announcement.announcement_receivers.each_with_index do |receiver, i| %>
          <span href="#" class="list_logo_item <%= i > 5 ? 'hidden' : ''%>">
            <% if receiver.receiver_type %>
              <% if receiver.brand.logo? %>
                <%= image_tag receiver.brand.logo.thumb_small, alt: '', title: receiver.brand.title %>
              <% else %>
                <%= receiver.brand.initial %>
              <% end %>
            <% else %>
              <% if receiver.startup.logo? %>
                <%= image_tag receiver.startup.logo.thumb_small, alt: '', title: receiver.startup.title %>
              <% else %>
                <%= receiver.startup.initial %>
              <% end %>
            <% end %>
          </span>
          <% counter += 1 if i > 5 %>
        <% end %>
        <% if counter > 0 %>
          <span href="#" class="show-hidden-users list_logo_item">
            <span>+ <%= counter %></span>
          </span>
        <% end %>
      <% else %>
        <%= announcement_users_text(@announcement) %>
      <% end %>
    </div>
  <% end %>
  <%= @announcement.content.html_safe %>
</div>

app/views/announcements/_slide_panels.html.erb
<div class="slide-panel from-right" data-btn="send_announcement">
  <div class="slide-panel-container">
    <div id="announcement-form" class="slide-panel-content slide-panel-content_pb">
    </div>
  </div>
</div>

<div class="slide-panel from-right no_translate_sliding visible_panel" data-btn="announcements_details">
  <div class="slide-panel-container">
    <div id="announcement-details" class="slide-panel-content slide-panel-content_no_padd">
    </div>
  </div>
</div>

<div class="slide-panel from-right" data-btn="announcements_preview">
  <div class="slide-panel-container">
    <div id="announcement-preview" class="slide-panel-content slide-panel-content_no_padd">
    </div>
  </div>
</div>

app/views/announcements/create.js.erb
$("#notification").html("<%= j(render('layouts/flash_message')) %>");
$('.top_notification').showFlashMessage();
<% if @announcement.errors.any? %>
  <% if remotipart_submitted? %>
    $("#announcement-form").html("<%= j "#{render('new')}" %>");
  <% else %>
    $("#announcement-form").html("<%= j(render 'new') %>");
  <% end %>
  $(".js-example-basic-multiple").select2({
    templateResult: formatImg
  });
  $('.send-to').each(function() {
    if ($(this).is(':checked')) {
      $(this).parents('label').addClass('active');
      if ($(this).val() == 'selected_u') {
        $('.hidden_selected_users').show();
      }
    } else {
      $(this).parents('label').removeClass('active');
    }
  });
  $('#announcement_content').froalaEditor({
    heightMin: '200px',
    toolbarButtons: ['bold', 'italic', 'underline', '|', 'insertImage', 'insertLink', '|', 'undo', 'redo', 'clearFormatting', 'html'],
    imageUploadURL: '<%= announcements_upload_image_path %>',
    imageUploadMethod: 'POST',
    imageUploadParams: {
      authenticity_token: '<%= form_authenticity_token %>',
      return_to: window.location.href
    }
  });
  $.mmvMethods.initEditor();
<% else %>
  $.controlMethods.hidePanel("send_announcement");
  if (!$("#announcement-list").length) {
    <% if remotipart_submitted? %>
      $("#empty-announcement").replaceWith("<%= j "#{render('index')}" %>");
    <% else %>
      $('#empty-announcement').replaceWith("<%= j(render 'index') %>");
    <% end %>
  }
  <% if remotipart_submitted? %>
    $("#announcement-list").prepend("<%= j "#{render('announcement', announcement: @announcement)}" %>");
  <% else %>
    $("#announcement-list").prepend("<%= j (render 'announcement', announcement: @announcement) %>");
  <% end %>
  $('.ellipsis_text').dotdotdot();
  $.controlMethods.removePlaceholder();
<% end %>

app/views/announcements/index.html.erb
<% if @announcements.empty? %>
  <%= render 'empty_announcement' %>
<% else %>
  <%= render 'index' %>
  <%= paginate @announcements %>
<% end %>

app/views/announcements/new.js.erb
$('#announcement-form').html("<%= j(render 'new') %>");
$.controlMethods.showPanel("send_announcement");
$("#receiver_ids").select2({
  templateResult: formatImg
});
$('#announcement_content').froalaEditor({
  heightMin: '200px',
  toolbarButtons: ['bold', 'italic', 'underline', '|', 'insertImage', 'insertLink', '|', 'undo', 'redo', 'clearFormatting', 'html'],
  imageUploadURL: '<%= announcements_upload_image_path %>',
  imageUploadMethod: 'POST',
  imageUploadParams: {
    authenticity_token: '<%= form_authenticity_token %>',
    return_to: window.location.href
  }
});
$.mmvMethods.initEditor();

function formatImg (state) {
  if (!state.id) { return state.text; }
  var $state = $(
    '<span><img src="' + state.element.getAttribute('data-img-src') + '" class="multiple_item_img" /> ' + state.text + '</span>'
  );
  return $state; 
};

app/views/announcements/preview.js.erb
<% if remotipart_submitted? %>
  $("#announcement-preview").html("<%= j "#{render('show')}" %>");
  $("#announcement-form").html("<%= j "#{render('new')}" %>");
<% else %>
  $("#announcement-preview").html("<%= j(render 'show') %>");
  $("#announcement-form").html("<%= j(render 'new') %>");
<% end %>
$.controlMethods.showPanel("announcements_preview");
$(".js-example-basic-multiple").select2({
  templateResult: formatImg
});
$('.send-to').each(function() {
  if ($(this).is(':checked')) {
    $(this).parents('label').addClass('active');
    if ($(this).val() == 'selected_u') {
      $('.hidden_selected_users').show();
    }
  } else {
    $(this).parents('label').removeClass('active');
  }
});
$('#announcement_content').froalaEditor({
  heightMin: '200px',
  toolbarButtons: ['bold', 'italic', 'underline', '|', 'insertImage', 'insertLink', '|', 'undo', 'redo', 'clearFormatting', 'html'],
  imageUploadURL: '<%= announcements_upload_image_path %>',
  imageUploadMethod: 'POST',
  imageUploadParams: {
    authenticity_token: '<%= form_authenticity_token %>',
    return_to: window.location.href
  }
});
$.mmvMethods.initEditor();

app/views/announcements/show.html.erb
<%= render partial: 'show', locals: { dont_show_exit: true } %>

app/views/announcements/show.js.erb
$('#announcement-details').html("<%= j(render 'show') %>");
$.controlMethods.showPanel("announcements_details");