config/routes.rb
Rails.application.routes.draw do

  match '/404', :to => 'errors#not_found', :via => :all

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }

  devise_scope :user do
    controller 'users/sessions' do
      get ':alias/sign_in' => :new, as: :new_brand_session
      post ':alias/sign_in' => :create, as: :brand_session
      root action: :new
    end
  end

  get '/dashboard', to: 'dashboard#index'
  resources :brands do
    resources :users, controller: 'brand_users' do
      member do
        get :activity
        get :diagnostic
      end
    end
    resources :startups, path_names: { new: 'push' }, controller: :brand_startups,
              only: [:index, :new, :create, :destroy] do
      get :delete, on: :member
    end
    member do
      patch :update_question
      delete :delete_question
      get :brief
      get :modify
      get :promo_pages
      get :settings
      controller :brands do
        patch 'refresh' => :refresh_persisted
      end
      get :delete
    end
    collection do
      post :create_question
      post 'refresh' => 'brands#refresh'
      get :search
    end
  end

  resources :email_templates
  resources :brand_questions
  resources :announcements
  post '/announcements/upload', to: 'announcements#upload_image',
                                as: :announcements_upload_image
  resources :users do
    member do
      post :reset_password
      get  :activity
      get  :diagnostic
    end
  end

  resources :activities do
    collection do
      get :requests
      get :updates
      get :my_tasks
      get :assigned_tasks
    end
  end

  resources :invites do
    get :new_startup, on: :collection
    get :delete, on: :member
  end

  resources :startups, path_names: { notes: 'comments' } do
    resources :announcements, controller: 'startup_announcements', only: [:index, :show]
    resources :tags, controller: :startup_tags, only: [:index, :create, :destroy]
    post :add_pdf
    delete 'destroy_pdf/:pdf_id' => 'startups#destroy_pdf', as: :destroy_pdf
    member do
      get :tags
      get :profile
      get :questions
      get :notes
      get :tasks
      get :home
      get :requests
      get :all_questions
      get :activity
      get :cabinet
      controller :startups do
        get 'push' => :new_push
        post 'push' => :create_push
        get 'add_to_list' => :new_add_to_list
        post 'add_to_list' => :create_add_to_list
      end
      get   :edit_watchlist
      patch :update_watchlist
      get   :delete
    end
    collection do
      put :cancel
      get :search
      get :watchlist
      post '/download/:type', to: 'startups#download', as: 'download'
    end
    resources :brief, controller: :startup_brief_summaries do
      get :to_step, on: :collection
    end
    resources :profile_questions, except: :destroy
  end

  resources :startup_brief_summaries

  resources :search do
    collection do
      post :quick
      get :quick
      get :saved
      get :advanced
      post :adv
      get :by_categories
      get 'adv', to: 'search#adv_filter'
      resources :tags, except: [:edit, :update] do
        collection do
          delete :delete_tag
        end
      end
    end
    member do
      get :edit_name
      patch :update_name
    end
  end

  resources :lists do
    get :remove_from, on: :member
    collection do
      get :search
      get :add_to_favorites
      get :remove_from_favorites
    end
  end
  put 'sort_lists', to: 'lists#sort', as: :sort_lists
  put 'reset_list_sorting', to: 'lists#reset_sorting', as: :reset_list_sorting

  resources :requests do
    get :seen, on: :member
  end
  resources :notes do
    resources :comments, controller: :note_comments, only: [:edit, :create, :update, :destroy]
    member do
      get :delete
      get :mark_as_done
      get :mark_as_undone
    end
  end

  resources :brand_brief_summaries
  resources :user_diagnostic_summaries

  scope 'settings' do
    get 'diagnostic', to: 'diagnostic#index'
    resources :diagnostic_questions
    resources :diagnostic_types, only: [:index, :edit, :update]
    resources :packages do
      get :delete, on: :member
    end
    resources :brand_brief do
      member do
        get :modify
      end
    end
    resources :promo_pages, except: [:show] do
      member do
        patch :update_question
        delete :delete_question
        get 'unpublish' => 'promo_pages#new_unpublish'
        patch :unpublish
        patch :reject
        patch :approve
        patch 'refresh' => 'promo_pages#refresh_persisted'
        get :view_questions
        get :preview
      end
      collection do
        post :create_question
        post 'refresh' => 'promo_pages#refresh'
        get :brand_questions
      end
    end
  end

  get '/promo/:alias', to: 'promo_pages#show', as: :promo

  scope path: '/startup_brand_brief', controller: :startup_brand_briefs do
    get ':brand_alias' => :new, as: :new_startup_brand_brief
    post ':brand_alias' => :create, as: :startup_brand_brief
  end

  scope path: '/startup_promo_brief', controller: :startup_promo_briefs do
    get ':promo_alias' => :new, as: :new_startup_promo_brief
    post ':promo_alias' => :create, as: :startup_promo_brief
  end


  resources :scorecards do
    collection do
      get 'show_by_token/:token' => 'scorecards#show_by_token', as: :show_by_token
      get 'cancel'
      post 'refresh'
      patch 'refresh_persisted'
      get 'download_list/:template_id' => 'scorecards#download_list', as: :download_list
      post 'generate_pdf' => 'scorecards#generate_pdf', as: :generate_pdf
      get 'search_startups'
    end
    patch 'push'
  end
  resources :scorecard_templates do
    get 'generate_xls'
    collection do
      patch 'refresh_persisted'
      post 'add_question'
      get 'cancel'
      post 'refresh'
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  enum status: [:assigned, :done]

  acts_as_paranoid

  COMMENT = 'comment'
  TASK = 'task'

  belongs_to :startup
  belongs_to :author,   class_name: 'User',
                        foreign_key: :author_id, unscoped: true
  belongs_to :assignee, class_name: 'User',
                        foreign_key: :assignee_id, unscoped: true
  has_many   :comments, class_name: 'NoteComment'

  validates :note_text, presence: true
  # validates :due_date, presence: true
  # validates :assignee_id, presence: true

  scope :reminders, ->(user_id) do
    where.not(assignee_id: nil)
    .where('author_id = :user_id OR assignee_id = :user_id', { user_id: user_id })
  end
  scope :tasks, -> { where.not assignee_id: nil }
  scope :author_or_assignee, -> (user) do
    where('author_id = :user_id OR assignee_id = :user_id', user_id: user.id)
  end

  delegate :full_name, to: :author, prefix: true
  delegate :photo, to: :author, prefix: true
  delegate :full_name, to: :assignee, prefix: true
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource

  before_action :find_note, only: [:edit, :update, :delete, :destroy,
                                   :mark_as_done, :mark_as_undone]

  before_action :find_startup, only: [:new, :create]

  def new
    @note = Note.new.decorate
  end

  def create
    @note = Note.new(note_params.merge(startup_id: @startup.id)).decorate
    if @note.save
      if @note.assignee_id?
        text = 'Task was added'
        method = :adding_task_activity
      else
        text = 'Comment was added'
        method = :adding_comment_activity
      end
      NoteService.new(@note, @startup).send(method, current_user)
      flash.now[:notice] = { title: 'Done', text: text }
    end
  end

  def update
    if @note.update_attributes(note_params)
      NoteService.new(@note, @note.startup).editing_note_activity(current_user)
      text = @note.assignee_id? ? 'Task was updated' : 'Comment was updated'
      flash.now[:notice] = { title: 'Done', text: text }
    end
  end

  def destroy
    @startup = @note.startup
    if @note.destroy
      NoteService.new(@note, @note.startup).deleting_note_activity(current_user)
      flash.now[:notice] = { title: 'Done', text: 'Has been successfully deleted' }
    end
  end

  def mark_as_done
    if @note.update_attributes(status: :done, status_changed_at: Date.today)
      NoteService.new(@note, @note.startup).marking_as_done_activity(current_user)
    end
  end

  def mark_as_undone
    @note.assigned!
  end

  private

  def note_params
    permit_params = params[:type] == Note::TASK ? [:assignee_id, :note_text, :due_date] : [:note_text]
    prms = params.require(:note).permit(permit_params).merge(author_id: current_user.id)

    if params[:note][:assignee_id].blank? && params[:type] == Note::TASK
      prms = prms.merge(assignee_id: current_user.id)
    end
    prms
  end

  def find_startup
    @startup = Startup.find_by(id: params[:startup_id])
  end

  def find_note
    @note = Note.find_by(id: params[:id]).decorate
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_assignee.html.erb
<div class="collapse_users">
  <a href="#send_reminder" class="collapse_user_link collapsed" data-toggle="collapse" aria-expanded="false" aria-controls="send_reminder">
    ASSIGN TASK TO <i class="icon icon_arrow_down"></i>
  </a>
  <div id="send_reminder" class="collapse" aria-expanded="false">
    <div class="btn-group btn_check_group" data-toggle="buttons">
      <%= f.collection_radio_buttons(:assignee_id, current_user.evo_team? ? User.evo_users : current_user.brand.users, :id, :full_name) do |b| %>
        <label class="<%= b.object.id == f.object.assignee_id ? "btn user_check active" : "btn user_check" %>">
          <%= b.radio_button(autocomplete: false) %>
          <span class="user_details">
            <span class="user_details_img <%= b.object.photo.thumb_small.present? ? '' : 'brand_img_holder' %>">
              <%= b.object.photo.thumb_small.present? ? image_tag(b.object.photo.thumb_small, alt:'Logo', width: 40) : b.object.initial %>
            </span>
            <span class="user_details_info">
              <span><%= b.object.f_name %></span>
              <span><%= b.object.l_name %></span>
            </span>
          </span>
        </label>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/_blank_list_item.html.erb
<div class="panel-heading clearfix placeholder_styles">
  <span class="panel_img">
    <span class="panel_img_holder"></span>
  </span>
  <div class="panel_info">
    <div class="panel_info_title"></div>
    <div class="panel_info_name_date clearfix">
      <span class="panel_info_name"></span>
      <span class="panel_info_date"></span>
    </div>
  </div>
</div>

app/views/notes/_comment.html.erb
<div id="noteComment<%= comment.id %>" class="answer_block">
  <div class="answer_title">COMMENT</div>
  <div class="panel_info_name_date clearfix">
    <span class="panel_info_name">By <%= comment.author.full_name %></span>
    <span class="panel_info_date"><%= comment.added_at %></span>
  </div>
  <% if can?(:update, comment) %>
    <%= link_to 'Edit', edit_note_comment_path(comment, note_id: comment.note.id),
       class: 'edit_panel_item', remote: true %>
   <% end %>
  <div class="answer_text">
    <%= auto_link(comment.body, html: { target: '_blank', class: 'pink_link' }) %>
  </div>
  <span class="panel_img_holder"><%= comment.author_photo %></span>
</div>

app/views/notes/_empty_notes.html.erb
<div class="empty_block empty_block_pt">
  <div class="curved_lines" style="left: 628.5px; bottom: 276px;"></div>
  <%= link_to '+Add New Comment', new_note_path(startup_id: @startup.id, type: 'comment'),
              class:'btn btn_add btn_in_empty absolute', remote: true  %>
  <i class="icon icon_doc_pen"></i>
  <h1 class="empty_title"><span class="empty_title_inner">Comments</span></h1>
  <p class="empty_text">Add a comment to share your thoughts about this startup with other team members</p>
</div>

app/views/notes/_empty_tasks.html.erb
<div class="empty_block empty_block_pt">
  <div class="curved_lines" style="left: 628.5px; bottom: 276px;"></div>
  <%= link_to '+ Add Task', new_note_path(startup_id: @startup.id, type: 'task'),
              class:'btn btn_add btn_in_empty absolute', remote: true  %>
  <i class="icon icon_checkboxes"></i>
  <h1 class="empty_title"><span class="empty_title_inner">Tasks</span></h1>
  <p class="empty_text">Assign a task to a teammate or send yourself a reminder</p>
</div>

app/views/notes/_index_notes.html.erb
<div class="head_content has_btn hidden-xs">
  <h1 class="h1_title">Comments</h1>
  <div class="subtitle">Leave comments about this startup for your team to read.</div>
  <%= link_to '+ Add New Comment', new_note_path(startup_id: @startup.id, type: 'comment'), remote: true, class:'btn btn_add' %>
</div>
<%= link_to '+ Add Comments', new_note_path(startup_id: @startup.id, type: 'comment'),
            class:'btn btn_open_panel btn_add btn_mobile visible-xs',
            data: { panel: 'add_note' }, remote: true %>
<div class="accordion_holder">
  <div class="panel-group startup_notes_table" id="accordion" role="tablist" aria-multiselectable="true">
    <%= render partial: 'notes/note', collection: @notes %>
  </div>
</div>

app/views/notes/_index_tasks.html.erb
<div class="head_content has_btn hidden-xs">
  <h1 class="h1_title">Tasks</h1>
  <div class="subtitle">Assign a task to an Evol8tion team member for this startup.</div>
  <%= link_to '+ Add Task', new_note_path(startup_id: @startup.id, type: 'task'), remote: true, class:'btn btn_add' %>
</div>
<%= link_to '+ Add Task', new_note_path(startup_id: @startup.id, type: 'task'),
            class:'btn btn_open_panel btn_add btn_mobile visible-xs',
            data: { panel: 'add_note' }, remote: true %>
<div class="accordion_holder">
  <div class="panel-group startup_notes_table" id="accordion" role="tablist" aria-multiselectable="true">
    <%= render partial: 'notes/note', collection: @tasks %>
  </div>
</div>

app/views/notes/_note.html.erb
<div id="note-<%= note.id %>" class="panel panel-default <%= note.task? %> <%= note.task_done %> note-<%= note.id %>">
  <div role="button" class="slide_accordion collapsed" data-toggle="collapse"
       data-parent="#accordion<%= note.id %>" href="#collapse<%= note.id %>"
       aria-expanded="false" aria-controls="collapse<%= note.id %>">
    <div class="panel-heading clearfix" role="tab" id="heading<%= note.id %>">
      <%= render 'blank_list_item' %>
      <span class="panel_img"><span class="panel_img_holder"><%= note.author_photo %></span></span>
      <div class="panel_info<%= ' panel_has_edit' unless note.assignee.present? %>">
        <div class="panel_info_title">
          <%= note.suffix %>
          <%= auto_link(note.note_text, html: { target: '_blank', class: 'pink_link' }) %>
        </div>
        <div class="panel_info_name_date clearfix">
          <span class="panel_info_name"><%= note.assigned_for %> <%= note.task_author %></span>
          <span class="panel_info_date"><%= note.assigned_at %></span>
        </div>
        <%= note.editable_or_done %>
      </div>
    </div>
  </div>
  <div id="collapse<%= note.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= note.id %>">
    <div class="panel-body">
      <div id="comments_<%= note.id %>">
        <%= render partial: '/notes/comment', collection: note.comments %>
      </div>
      <div id="comment_form_<%= note.id %>">
        <%= render '/note_comments/new', note: note %>
      </div>
    </div>
  </div>
  <div class="checkbox checkbox_in_panel <%= note.date_fail %>">
    <div class="checkbox_item">
      <% if note.assignee.present? && can?(:mark_task, note) %>
        <%= link_to note.mark_unmark_url, class: 'check_activity mark_note', remote: true do %>
          <label for="check_<%= note.id %>"><%= note.due_date_at %></label>
        <% end %>
        <span class="check_icon_holder"><i class="icon icon_mark"></i></span>
      <% end %>
    </div>
  </div>
  <a href="#" class="close_accordion_item"><i class="icon icon_arrow_up"></i></a>
</div>

app/views/notes/create.js.erb
<% if @note.errors.empty? %>
  if ($("#startup_notes").find(".empty_block").length > 0) {
    $("#startup_notes").html("<%= j(render @note.assignee.present? ? 'index_tasks' : 'index_notes') %>");
  }
  $("<%= j render 'note', note: @note %>").prependTo("#accordion");
  $.controlMethods.hidePanel("add_note");
  $("#notification").html("<%= j(render('layouts/flash_message')) %>")
  $('.top_notification').addClass('sm_size').showFlashMessage()
<% else %>
  $("#note_form").html("<%= j render 'new' %>");
  $.myMethods.calendar_init();
<% end %>
$.controlMethods.removePlaceholder();

app/views/notes/destroy.js.erb
$("#note-<%= @note.id %>").remove();

if ($("#startup_notes").find(".panel").length == 0) {
  $("#startup_notes").html("<%= j(render @note.assignee.present? ? 'empty_tasks' : 'empty_notes') %>");
}
$.controlMethods.hidePanel("add_note");
$("#notification").html("<%= j(render('layouts/flash_message')) %>");
if ($(".activity_holder").length) {
  $('.top_notification').showFlashMessage();
} else {
  $('.top_notification').addClass('sm_size').showFlashMessage();
}

app/views/notes/edit.js.erb
el = $("#note_form")
el.html("<%= j render 'new' %>")
$.controlMethods.showPanel("add_note")
$.myMethods.calendar_init()

app/views/notes/mark_as_undone.js.erb
$(".note-<%= @note.id%>").replaceWith("<%= j render 'notes/note', note: @note %>")
$.controlMethods.removePlaceholder();

app/views/notes/new.js.erb
$("#note_form").html("<%= j render 'new' %>");
$.controlMethods.showPanel("add_note");
$.myMethods.calendar_init();

app/views/notes/update.js.erb
<% if @note.errors.any? %>
  $("#note_form").html("<%= j render 'new' %>")
  $.myMethods.calendar_init();
<% else %>
  $("#note-<%= @note.id %>").replaceWith("<%= j(render 'note', note: @note) %>");
  $.controlMethods.hidePanel("add_note");
  $.controlMethods.removePlaceholder();
  $("#notification").html("<%= j(render('layouts/flash_message')) %>");
  if ($(".activity_holder").length) {
    $('.top_notification').showFlashMessage();
  } else {
    $('.top_notification').addClass('sm_size').showFlashMessage();
  }
<% end %>