config/routes.rb
Rails.application.routes.draw do

  match '/404', :to => 'errors#not_found', :via => :all

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }

  devise_scope :user do
    controller 'users/sessions' do
      get ':alias/sign_in' => :new, as: :new_brand_session
      post ':alias/sign_in' => :create, as: :brand_session
      root action: :new
    end
  end

  get '/dashboard', to: 'dashboard#index'
  resources :brands do
    resources :users, controller: 'brand_users' do
      member do
        get :activity
        get :diagnostic
      end
    end
    resources :startups, path_names: { new: 'push' }, controller: :brand_startups,
              only: [:index, :new, :create, :destroy] do
      get :delete, on: :member
    end
    member do
      patch :update_question
      delete :delete_question
      get :brief
      get :modify
      get :promo_pages
      get :settings
      controller :brands do
        patch 'refresh' => :refresh_persisted
      end
      get :delete
    end
    collection do
      post :create_question
      post 'refresh' => 'brands#refresh'
      get :search
    end
  end

  resources :email_templates
  resources :brand_questions
  resources :announcements
  post '/announcements/upload', to: 'announcements#upload_image',
                                as: :announcements_upload_image
  resources :users do
    member do
      post :reset_password
      get  :activity
      get  :diagnostic
    end
  end

  resources :activities do
    collection do
      get :requests
      get :updates
      get :my_tasks
      get :assigned_tasks
    end
  end

  resources :invites do
    get :new_startup, on: :collection
    get :delete, on: :member
  end

  resources :startups, path_names: { notes: 'comments' } do
    resources :announcements, controller: 'startup_announcements', only: [:index, :show]
    resources :tags, controller: :startup_tags, only: [:index, :create, :destroy]
    post :add_pdf
    delete 'destroy_pdf/:pdf_id' => 'startups#destroy_pdf', as: :destroy_pdf
    member do
      get :tags
      get :profile
      get :questions
      get :notes
      get :tasks
      get :home
      get :requests
      get :all_questions
      get :activity
      get :cabinet
      controller :startups do
        get 'push' => :new_push
        post 'push' => :create_push
        get 'add_to_list' => :new_add_to_list
        post 'add_to_list' => :create_add_to_list
      end
      get   :edit_watchlist
      patch :update_watchlist
      get   :delete
    end
    collection do
      put :cancel
      get :search
      get :watchlist
      post '/download/:type', to: 'startups#download', as: 'download'
    end
    resources :brief, controller: :startup_brief_summaries do
      get :to_step, on: :collection
    end
    resources :profile_questions, except: :destroy
  end

  resources :startup_brief_summaries

  resources :search do
    collection do
      post :quick
      get :quick
      get :saved
      get :advanced
      post :adv
      get :by_categories
      get 'adv', to: 'search#adv_filter'
      resources :tags, except: [:edit, :update] do
        collection do
          delete :delete_tag
        end
      end
    end
    member do
      get :edit_name
      patch :update_name
    end
  end

  resources :lists do
    get :remove_from, on: :member
    collection do
      get :search
      get :add_to_favorites
      get :remove_from_favorites
    end
  end
  put 'sort_lists', to: 'lists#sort', as: :sort_lists
  put 'reset_list_sorting', to: 'lists#reset_sorting', as: :reset_list_sorting

  resources :requests do
    get :seen, on: :member
  end
  resources :notes do
    resources :comments, controller: :note_comments, only: [:edit, :create, :update, :destroy]
    member do
      get :delete
      get :mark_as_done
      get :mark_as_undone
    end
  end

  resources :brand_brief_summaries
  resources :user_diagnostic_summaries

  scope 'settings' do
    get 'diagnostic', to: 'diagnostic#index'
    resources :diagnostic_questions
    resources :diagnostic_types, only: [:index, :edit, :update]
    resources :packages do
      get :delete, on: :member
    end
    resources :brand_brief do
      member do
        get :modify
      end
    end
    resources :promo_pages, except: [:show] do
      member do
        patch :update_question
        delete :delete_question
        get 'unpublish' => 'promo_pages#new_unpublish'
        patch :unpublish
        patch :reject
        patch :approve
        patch 'refresh' => 'promo_pages#refresh_persisted'
        get :view_questions
        get :preview
      end
      collection do
        post :create_question
        post 'refresh' => 'promo_pages#refresh'
        get :brand_questions
      end
    end
  end

  get '/promo/:alias', to: 'promo_pages#show', as: :promo

  scope path: '/startup_brand_brief', controller: :startup_brand_briefs do
    get ':brand_alias' => :new, as: :new_startup_brand_brief
    post ':brand_alias' => :create, as: :startup_brand_brief
  end

  scope path: '/startup_promo_brief', controller: :startup_promo_briefs do
    get ':promo_alias' => :new, as: :new_startup_promo_brief
    post ':promo_alias' => :create, as: :startup_promo_brief
  end


  resources :scorecards do
    collection do
      get 'show_by_token/:token' => 'scorecards#show_by_token', as: :show_by_token
      get 'cancel'
      post 'refresh'
      patch 'refresh_persisted'
      get 'download_list/:template_id' => 'scorecards#download_list', as: :download_list
      post 'generate_pdf' => 'scorecards#generate_pdf', as: :generate_pdf
      get 'search_startups'
    end
    patch 'push'
  end
  resources :scorecard_templates do
    get 'generate_xls'
    collection do
      patch 'refresh_persisted'
      post 'add_question'
      get 'cancel'
      post 'refresh'
    end
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  EVO_SUBMISSIONS = [['All', 'all_startups'], ['Founder Evol8tion', 'founder_evolution'],
                 ['Evol8tion Generated', 'evo_generated'], ['Founder - Brand', 'founder_brand'],
                 ['Watchlist', 'watchlist']].freeze


  BRAND_SUBMISSIONS = [['All', 'all_startups'], ['Founder Submitted', 'founder'],
                       ['Evol8tion Curated', 'evolution'], ['Watchlist', 'watchlist']].freeze

  belongs_to :user
  has_many :search_categories, dependent: :destroy, autosave: true
  has_many :category_values, through: :search_categories

  scope :saved_search, -> (user) do
    user_ids(user).includes(:user).order(updated_at: :desc)
  end

  scope :user_search, -> (id, user)  do
    user_ids(user).where(id: id).includes(:category_values).first
  end

  scope :user_ids, -> (user) do
    user_ids = case
      when user.brand_team?
        user.brand_user_ids
      when user.evo_team?
        User.evo_users.pluck(:id)
      else
        []
      end
    where(user_id: user_ids)
  end

  validates :name, presence: true
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include SearchHelper
  include ApplicationHelper
  before_action :user_search, only: [:edit, :update, :show, :destroy, :edit_name, :update_name]
  before_action :categories, only: [:new, :edit, :create, :update, :advanced]
  before_action :advanced_search, only: [:adv]
  before_action :check_session, only: [:adv_filter, :create, :update]
  before_action :favorite_list, only: [:quick, :adv, :show]
  before_action :clear_session, only: [:show]
  before_action :get_tags_count, only: [:advanced_search, :quick, :adv, :show,
                                        :adv_filter]
  after_action :saving_search_activity, only: [:create]
  after_action :updating_search_activity, only: [:update, :update_name]
  after_action :save_url, only: [:quick, :adv, :adv_filter]
  after_action :set_download_startup_ids, only: [:quick, :adv, :by_categories, :show, :check_session, :adv_filter]

  load_and_authorize_resource

  def quick
    if params[:search].blank?
      @startups = []
    else
      startups = Startup.all_startups(current_user)
      tag_titles = params[:search][0] == '#' ? params[:search][1..-1] : ''

      @startups = Startup.search params[:search],
        page: params[:page], per_page: 25,
        sql: { include: [:lists, :owner, :invite, :promo_briefs] },
        with: { id: startups.any? ? startups.pluck(:id) : 0 },
        conditions: { tag_titles: tag_titles },
        order: sort_column + " " + sort_direction
      get_startup_tags
    end
    session[:back_search_result] = params
  end

  def by_categories
    @back_link = params[:back_link].present? ? params[:back_link] : dashboard_url
    if params[:search].present?
      category_values = CategoryValue
        .where(id: params[:search][:category_value_ids]).select(:id, :content, :icon_name)
    else
      category_values = CategoryValue.all.select(:id, :content, :icon_name)
    end
    @search_params = {
      search: { category_value_ids: category_values.collect(&:id),
                startup_type: :all_startups }
    }
    @custom_search_query = category_values.collect(&:content).join(', ')
    @custom_search_icon = 'icon__' + category_values.last.icon_name
    @back_title = 'X Close'
    advanced_search

    render :by_categories, layout: 'dashboard'
  end

  def adv
    session[:new_advanced_search] = search_params
    if params[:search][:id]
      session[:new_advanced_search][:id] = params[:id] = params[:search][:id]
      user_search
    else
      new_search
    end
  end

  def adv_filter
  end

  def advanced
    if params[:back_to_form].present? && params[:search].present?
      @search = Search.new search_form_params
    elsif params[:back_search].blank? || session[:back_search_result].blank?
      new_search
    else
      backsearch = session[:back_search_result][:search]
      backsearch.delete(:name)
      backsearch.delete(:startups)
      @search = Search.new(backsearch.permit!)
    end
  end

  def saved
    @searches = Search.saved_search(current_user)
  end

  def show
    params[:search] = @search.attributes
    params[:search][:category_value_ids] = @search.category_values.ids
    advanced_search
    render layout: 'layouts/startup/search'
  end

  def new
    new_search
  end

  def edit
  end

  def create
    @search = Search.new(search_params)
    if @search.save
      clear_session
      flash.now[:notice] = { title: 'Done', text: 'Advanced Search was successfully saved.' }
    else
      flash.now[:error] = { title: 'Done', text: 'Advanced Search saved error.' }
    end
  end

  def update
    @search.update_attributes(search_params)
    if @search.errors.empty?
      clear_session
      flash.now[:notice] = { title: 'Done', text: 'Advanced search was successfully updated.' }
    else
      flash.now[:error] = { title: 'Done', text: 'Advanced search update error.' }
    end
  end

  def destroy
    if @search.nil?
      flash.now[:error] = { title: 'Done', text: 'Advanced search couldn\'t be destroyed' }
    else
      @search.destroy
      @searches_count = Search.saved_search(current_user).count
      flash.now[:notice] = { title: 'Done', text: 'Advanced search successfully deleted.' }
    end
  end

  def edit_name
  end

  def update_name
    @search.update_attributes(save_name)
    if @search.errors.empty?
      flash.now[:notice] = { title: 'Done', text: 'Advanced search name was successfully updated.' }
    else
      flash.now[:error] = { title: 'Done', text: 'Advanced search name update error.' }
    end
  end

  private

  def search_params
    params.require(:search).permit(
      :name,
      :location,
      :search,
      :added_from,
      :added_to,
      :startup_type,
      category_value_ids: []
    ).merge(user_id: current_user.id, number_startups: @startups.count)
  end

  def set_download_startup_ids
    session[:download_startup_ids] =
      @startups.any? ?  @startups.per(@startups.total_count).page(1).map(&:id) : []
  end

  def search_form_params
    params.require(:search).permit(
      :name,
      :location,
      :search,
      :added_from,
      :added_to,
      :startup_type,
      category_value_ids: []
    )
  end

  def user_search
    @search = Search.user_search(params[:id], current_user)
  end

  def categories
    @categories = Category.all.includes(:category_values)
    if current_user.evo_team?
      @submissions = Search::EVO_SUBMISSIONS
    else
      @submissions = Search::BRAND_SUBMISSIONS
    end
  end

  def advanced_search
    search = params[:search]
    startups = Startup.send(search[:startup_type], current_user)
    params[:search][:startups] = startups.pluck(:id) if startups.any?
    if params[:search][:search].blank? && advanced_conditions.blank? &&
       advanced_with_all.blank? && advanced_with.blank? && startups.blank?
      @startups = []
    else
      tag_titles = search[:search] && search[:search][0] == '#' ? search[:search][1..-1] : ''
      @startups = Startup.search search[:search],
        page: 1, per_page: startups.count,
        sql: { include: [:lists, :owner, :invite, :promo_briefs] },
        conditions: advanced_conditions,
        with_all: {:answer_id => advanced_with_all },
        with: advanced_with,
        conditions: { tag_titles: tag_titles },
        order: sort_column + " " + sort_direction
      @startups = Kaminari.paginate_array(@startups).page(params[:page]).per(25)
      get_startup_tags
    end
    params[:search][:startups] = nil
    session[:back_search_result] = params
  end

  def check_session
    if session[:new_advanced_search]
      session[:new_advanced_search][:name] = params[:search][:name] unless params[:search].nil?
      params[:search] = session[:new_advanced_search]
    end
    advanced_search
  end

  def favorite_list
    @favorite_list = List.includes(:startups).favorite_list(current_user)
  end

  def save_name
    params.require(:search).permit(:name)
  end

  def clear_session
    session[:new_advanced_search] = nil
  end

  def new_search
    @search = Search.new
  end

  def get_tags_count
    @tag_counts = StartupTag.where(user_id: current_user.evo_team? ?
                                            User.evo_users.pluck(:id) :
                                            current_user.brand_user_ids)
                            .group(:startup_id)
                            .count(:id)
  end

  def get_startup_tags
    startup_ids = []
    @startups.each { |s| startup_ids << s.id }
    @startup_tags = StartupTag.startup_tags(startup_ids, current_user.team_mate_ids)
  end

  def saving_search_activity
    return false if @search.invalid?

    activity_alias = current_user.evo_team? ? 'saved_search_created_by_evo' : 'saved_search_created_by_brand'
    activity = Activity.find_by(alias: activity_alias)

    texts = Activity.prepare_texts(patterns: { brand: activity[:brand_pattern],
                                               evo: activity[:evo_pattern] },
                                   replaces: ['{{user_name}}', '{{search_name}}'],
                                   replacements: [current_user.full_name, @search.name])

    UserActivity.create(user: current_user, activity: activity,
                        evo_text: texts[:evo], brand_text: texts[:brand])
  end

  def updating_search_activity
    return false if @search.invalid?

    if @search.previous_changes.any?
      activity_alias = current_user.evo_team? ? 'saved_search_edited_by_evo' : 'saved_search_edited_by_brand'
      activity = Activity.find_by(alias: activity_alias)

      texts = Activity.prepare_texts(patterns: { brand: activity[:brand_pattern],
                                                 evo: activity[:evo_pattern] },
                                     replaces: ['{{user_name}}', '{{search_name}}'],
                                     replacements: [current_user.full_name, @search.name])

      UserActivity.create(user: current_user, activity: activity,
                          evo_text: texts[:evo], brand_text: texts[:brand])
    end
  end

  def save_url
    session[:search_back] = {
      action: action_name,
      search: session[:back_search_result]
    }
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def advanced_conditions
    search = {}
    search[:location] = params[:search][:location] unless params[:search][:location].blank?
    search
  end

  def advanced_with
    search = {}
    sp = params[:search]
    if !sp[:added_to].blank?
      unless sp[:added_from].blank?
        search[:date_founded] = sp[:added_from].to_time.to_i..(sp[:added_to].to_time + 1.day).to_i
      else
        search[:date_founded] = Time.new(2000).to_i..(sp[:added_to].to_time + 1.day).to_time.to_i
      end
    elsif !sp[:added_from].blank?
      search[:date_founded] = sp[:added_from].to_time.to_i..Time.now.to_i
    end
    search[:id] = sp[:startups] unless sp[:startups].nil?
    search
  end

  def advanced_with_all
    with_all = {}
    sp = params[:search]
    answer_ids = sp[:category_value_ids].reject(&:blank?) unless sp[:category_value_ids].nil?

    return with_all if answer_ids.blank?
    category_values = CategoryValue.where(id: answer_ids)

    category_values.each do |cv|
      if with_all.has_key?(cv.category_id)
        with_all[cv.category_id] << cv.id
      else
        with_all[cv.category_id] = [cv.id]
      end
    end

    with_all.values
  end
end

app/views/search/_adv_filter.html.erb
<h2 class="mobile_title visible-xs">All Startups</h2>
<div class="boxer hovered styled_list">
  <%= render 'startups/header' %>
  <div id="startups-index">
    <%= render partial: '/startups/startup', collection: @startups %>
    <%= paginate @startups, remote: true %>
  </div>
</div>

app/views/search/_advanced.html.erb
<div class="top_panel clearfix advanced-search-results">
  <div class="top_panel_text_holder pull-left">
    <div class="top_panel_text">
      <%= link_to advanced_search_index_path(search: params[:search], back_to_form: true), class: 'top_panel_link' do %>
        <span class="top_panel_action">ADVANCED SEARCH <i class="icon icon_arrow_down"></i></span>
      <% end %>
      <!-- <a id="close-advance-result" href="#" class="top_panel_link<%# ' not-advanced' unless params[:is_advanced_page].present? || params[:back_result].present? %>">
        <span class="top_panel_action">ADVANCED SEARCH <i class="icon icon_arrow_down"></i></span>
      </a> -->
    </div>
  </div>
  <a class="btn btn_bordered_const pull-right save-advanced-query" href="#">Save Query</a>
  <div class="hidden_form">
    <div class="row">
      <div id="query-name-from" class="hidden_form_content col-lg-12">
        <%= render partial: 'search_name' %>
      </div>
    </div>
  </div>
</div>

<% if @startups.count > 0 %>
  <%= render '/startups/filter_startups' %>

  <div class="list_holder">
    <h2 class="mobile_title visible-xs">All Startups</h2>
    <div class="boxer hovered styled_list">
      <%= render 'startups/header' %>
      <div id="startups-index">
        <%= render partial: '/startups/startup', collection: @startups %>
        <%= paginate @startups, remote: true %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'search/nothing_found' %>
<% end %>

app/views/search/_empty_saved.html.erb
<div class="empty_block empty_block_pt">
  <i class="icon icon_clock_search"></i>
  <h1 class="empty_title">You have no saved searches.</h1>
  <p class="empty_text">Once you or a team member creates and save a search query it will appear here-<br>making it easy to continue to requery!</p>
</div>

app/views/search/_new.html.erb
<%= render partial: 'form' %>

app/views/search/_nothing_found.html.erb
<div class="empty_block empty_block_pt">
  <i class="icon icon_search"></i>
  <h1 class="empty_title">Nothing Found</h1>
  <p class="empty_text">Try other query. No results matched your search terms</p>
</div>

app/views/search/_search.html.erb
<li id="search-<%= search.id %>">
  <%= link_to search_path(search.id), { class: 'card_item md_size searched_card', id: "search-block-#{search.id}" } do %>
    <%= render 'blank_search' %>
    <span class="card_middle_block">
      <h3 class="card_title">
        <%= search.name %>
      </h3>
      <span class="card_subtitle">
        <%= pluralize(search.number_startups, 'startup') %> found
      </span>
    </span>
    <span class="card_bot_block">
      <span class="user_details">
        <span class="image-border user_details_img">
          <%= image_tag(search.user.photo? ? search.user.photo.thumb_small : 'user_mask.png', width: 40 ) %>
        </span>
        <span class="user_details_info">
          <span>By <%= search.user.full_name %></span>
          <span><%= search.updated_at.strftime("%d %B, %Y at %H:%M %P") %></span>
        </span>
      </span>
      <% if can? :edit_name, search %>
        <span class="edit_card" data-path="<%= edit_name_search_path(search) %>"><i class="icon icon_edit"></i></span>
      <% end %>
    </span>
  <% end %>
  <div id="edit-search-name-<%= search.id %>" class="add_card_block with_delete">
  </div>
  <div class="card_alert">
    <div class="card_alert_content">
      <i class="icon icon_info"></i>
      <div class="card_alert_title">
        Are You Sure?
      </div>
      <div class="card_alert_text">
        You will not be able to undo this action.
      </div>
    </div>
    <div class="add_card_btns clearfix">
      <button class="btn btn_default btn_gray btn_cancel_remove">CANCEL</button>
      <%= link_to search_path(search), remote: true, method: :delete, class:'btn btn_default btn_red btn_show_mark btn_remove_card' do %>
        <span>DELETE</span> <i class="icon icon_mark"></i>
      <% end %>
    </div>
  </div>
</li>

app/views/search/_show.html.erb
<% if @startups.any? %>
  <div class="list_holder">
    <div class="boxer hovered styled_list">
      <%= render 'startups/header' %>
      <%= render partial: '/startups/startup', collection: @startups %>
      <%= paginate @startups, remote: true %>
    </div>
  </div>
<% else %>
  <%= render 'nothing_found' %>
<% end %>

app/views/search/adv_filter.js.erb
$('.list_holder').html("<%= j(render 'adv_filter') %>");
$.controlMethods.removePlaceholder();

app/views/search/by_categories.html.erb
<div class="heading hidden-xs clearfix">
  <div class="dropdown dropdown_text custom_dropdown with_round_triangle pull-left">
    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Arrange by <i class="icon icon_arrow_down"></i></a>
    <ul class="dropdown-menu" id="menu1">
      <li data-sort="title_asc" class="sort-type">
        <%= sortable_startup "title", "Startup Name: A - Z", "asc", params[:type], @search_params %>
      </li>
      <li data-sort="title_desc" class="sort-type">
        <%= sortable_startup "title", "Startup Name: Z - A", "desc", params[:type], @search_params %>
      </li>
      <li data-sort="location_asc" class="sort-type">
        <%= sortable_startup "location", "Location A-Z", "asc", params[:type], @search_params %>
      </li>
      <li data-sort="location_asc" class="sort-type">
        <%= sortable_startup "location", "Location Z-A", "desc", params[:type], @search_params %>
      </li>
      <li class="active sort-type" data-sort="created_at_asc" class="sort-type">
        <%= sortable_startup "brands_startups.created_at", "Date Added: Newest to Oldest", "desc", params[:type], @search_params %>
      </li>
      <li data-sort="created_at_desc" class="sort-type">
        <%= sortable_startup "created_at", "Date Added: Oldest to Newest", "asc", params[:type], @search_params %>
      </li>
    </ul>
  </div>

  <%= render 'startups/export' %>
</div>


<%= render partial: "show" %>

app/views/search/by_categories.js.erb
$('.list_holder').html("<%= j(render 'show') %>");
$.controlMethods.removePlaceholder();

app/views/search/new.js.erb
$('#search-container').html("<%= j(render 'new') %>");
$.searchMethods.initCalendar();
$.searchMethods.initSelect();
$('.top_bar.advanced-search').addClass('active');

app/views/search/saved.html.erb
<div id="saved_searches">
  <% if @searches.empty? %>
      <%= render 'empty_saved' %>
  <% else %>
    <div class="cards_holder clearfix">
      <h2 class="mobile_title visible-xs">Saved Searches</h2>
      <ul class="card_list clearfix">
        <%= render partial: "search/search", collection: @searches %>
      </ul>
    </div>
  <% end %>
</div>

app/views/search/update.js.erb
$("#notification").html("<%= j(render('layouts/flash_message')) %>");
$('.top_notification').showFlashMessage();
<% if @search.errors.any? %>
  <% if params[:session_search] %>
    $("#query-name-from").html("<%= j(render 'search_name') %>");
  <% else %>
    $('#search-container').html("<%= j(render 'form') %>");
    $('.btn_save_query').click();
    $.searchMethods.initCalendar();
    $.searchMethods.initSelect();
    $('.bot_control_btns').addClass('error_search_name');
  <% end %>
<% else %>
  $('.btn_save_query_name').addClass('active');
  $('.btn_save_query_name').parents('.hidden_form').delay(1500).fadeOut('fast');
  <% if params[:session_search] %>
    setTimeout(function(){
        window.location = "<%= saved_search_index_path %>"
    }, 2000);
  <% else %>
    setTimeout(function(){
      $('.close_advance_search').click();
      $('.content').html("<%= j(render 'show') %>");
    }, 2000);
  <% end %>
<% end %>

app/views/search/update_name.js.erb
form = $('#edit-search-name-<%= @search.id %>');
item = $("#search-block-<%= @search.id %>");

<% if @search.errors.any? %>
  form.html("<%= j(render partial: 'edit_name') %>")
<% else %>
  window.setTimeout(function(){
    $("#search-<%= @search.id %>").replaceWith("<%= j render partial: 'search', locals: { search: @search } %>");
    $.controlMethods.removePlaceholder();
  }, 100);
  item.siblings('.add_card_block').find('.btn_invite_card').addClass('active');
  item.siblings('.add_card_block').fadeOut(400);
  $("#notification").html("<%= j(render('layouts/flash_message')) %>");
  $('.top_notification').showFlashMessage();
<% end %>