config/routes.rb
Rails.application.routes.draw do

  match '/404', :to => 'errors#not_found', :via => :all

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }

  devise_scope :user do
    controller 'users/sessions' do
      get ':alias/sign_in' => :new, as: :new_brand_session
      post ':alias/sign_in' => :create, as: :brand_session
      root action: :new
    end
  end

  get '/dashboard', to: 'dashboard#index'
  resources :brands do
    resources :users, controller: 'brand_users' do
      member do
        get :activity
        get :diagnostic
      end
    end
    resources :startups, path_names: { new: 'push' }, controller: :brand_startups,
              only: [:index, :new, :create, :destroy] do
      get :delete, on: :member
    end
    member do
      patch :update_question
      delete :delete_question
      get :brief
      get :modify
      get :promo_pages
      get :settings
      controller :brands do
        patch 'refresh' => :refresh_persisted
      end
      get :delete
    end
    collection do
      post :create_question
      post 'refresh' => 'brands#refresh'
      get :search
    end
  end

  resources :email_templates
  resources :brand_questions
  resources :announcements
  post '/announcements/upload', to: 'announcements#upload_image',
                                as: :announcements_upload_image
  resources :users do
    member do
      post :reset_password
      get  :activity
      get  :diagnostic
    end
  end

  resources :activities do
    collection do
      get :requests
      get :updates
      get :my_tasks
      get :assigned_tasks
    end
  end

  resources :invites do
    get :new_startup, on: :collection
    get :delete, on: :member
  end

  resources :startups, path_names: { notes: 'comments' } do
    resources :announcements, controller: 'startup_announcements', only: [:index, :show]
    resources :tags, controller: :startup_tags, only: [:index, :create, :destroy]
    post :add_pdf
    delete 'destroy_pdf/:pdf_id' => 'startups#destroy_pdf', as: :destroy_pdf
    member do
      get :tags
      get :profile
      get :questions
      get :notes
      get :tasks
      get :home
      get :requests
      get :all_questions
      get :activity
      get :cabinet
      controller :startups do
        get 'push' => :new_push
        post 'push' => :create_push
        get 'add_to_list' => :new_add_to_list
        post 'add_to_list' => :create_add_to_list
      end
      get   :edit_watchlist
      patch :update_watchlist
      get   :delete
    end
    collection do
      put :cancel
      get :search
      get :watchlist
      post '/download/:type', to: 'startups#download', as: 'download'
    end
    resources :brief, controller: :startup_brief_summaries do
      get :to_step, on: :collection
    end
    resources :profile_questions, except: :destroy
  end

  resources :startup_brief_summaries

  resources :search do
    collection do
      post :quick
      get :quick
      get :saved
      get :advanced
      post :adv
      get :by_categories
      get 'adv', to: 'search#adv_filter'
      resources :tags, except: [:edit, :update] do
        collection do
          delete :delete_tag
        end
      end
    end
    member do
      get :edit_name
      patch :update_name
    end
  end

  resources :lists do
    get :remove_from, on: :member
    collection do
      get :search
      get :add_to_favorites
      get :remove_from_favorites
    end
  end
  put 'sort_lists', to: 'lists#sort', as: :sort_lists
  put 'reset_list_sorting', to: 'lists#reset_sorting', as: :reset_list_sorting

  resources :requests do
    get :seen, on: :member
  end
  resources :notes do
    resources :comments, controller: :note_comments, only: [:edit, :create, :update, :destroy]
    member do
      get :delete
      get :mark_as_done
      get :mark_as_undone
    end
  end

  resources :brand_brief_summaries
  resources :user_diagnostic_summaries

  scope 'settings' do
    get 'diagnostic', to: 'diagnostic#index'
    resources :diagnostic_questions
    resources :diagnostic_types, only: [:index, :edit, :update]
    resources :packages do
      get :delete, on: :member
    end
    resources :brand_brief do
      member do
        get :modify
      end
    end
    resources :promo_pages, except: [:show] do
      member do
        patch :update_question
        delete :delete_question
        get 'unpublish' => 'promo_pages#new_unpublish'
        patch :unpublish
        patch :reject
        patch :approve
        patch 'refresh' => 'promo_pages#refresh_persisted'
        get :view_questions
        get :preview
      end
      collection do
        post :create_question
        post 'refresh' => 'promo_pages#refresh'
        get :brand_questions
      end
    end
  end

  get '/promo/:alias', to: 'promo_pages#show', as: :promo

  scope path: '/startup_brand_brief', controller: :startup_brand_briefs do
    get ':brand_alias' => :new, as: :new_startup_brand_brief
    post ':brand_alias' => :create, as: :startup_brand_brief
  end

  scope path: '/startup_promo_brief', controller: :startup_promo_briefs do
    get ':promo_alias' => :new, as: :new_startup_promo_brief
    post ':promo_alias' => :create, as: :startup_promo_brief
  end


  resources :scorecards do
    collection do
      get 'show_by_token/:token' => 'scorecards#show_by_token', as: :show_by_token
      get 'cancel'
      post 'refresh'
      patch 'refresh_persisted'
      get 'download_list/:template_id' => 'scorecards#download_list', as: :download_list
      post 'generate_pdf' => 'scorecards#generate_pdf', as: :generate_pdf
      get 'search_startups'
    end
    patch 'push'
  end
  resources :scorecard_templates do
    get 'generate_xls'
    collection do
      patch 'refresh_persisted'
      post 'add_question'
      get 'cancel'
      post 'refresh'
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  paginates_per 100

  has_many :startup_tags
  has_many :startups, through: :startup_tags

  scope :search_by_title, -> (search) { where('lower(title) like ?', "%#{search.downcase}%")}

  class << self
    def save_tags(tag_titles, user)
      titles = tag_titles.split(%r{,\s*})

      tags, tags_for_save = [], []
      titles.each do |title|
        tags_for_save << { title: title, alias: title.downcase.underscore }
      end
      user_ids = user.evo_team? ? User.evo_users.pluck(:id) : user.brand_user_ids
      tags_for_save.each do |tag|
        tags << Tag.find_or_create_by(alias: tag[:alias], user_id: user_ids) do |t|
          t.title, t.alias, t.user_id = tag[:title], tag[:alias], user.id
        end
      end
      tags
    end

  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include ApplicationHelper
  # load_and_authorize_resource

  before_action :find_tag, only: :show
  after_action :set_download_startup_ids, only: [:show]

  def index
    user_ids = current_user.evo_team? ? User.evo_users.pluck(:id)
                                      : current_user.brand_user_ids
    @tags = Tag.where(user_id: user_ids)
    @search = params[:search]
    @tags = @tags.search_by_title(@search) if @search
    @tags = @tags.page(params[:page])
  end

  def new
    @startup = Startup.find_by(id: params[:startup_id])
    @tag = Tag.new
  end

  # TODO: if add pagination for startups, you need uncomment line in set_download_startup_ids method
  def show
    user_ids = current_user.evo_team? ? User.evo_users.pluck(:id)
                                      : current_user.brand_user_ids

    @startups = @tag.startups.where(tags: { user_id: user_ids })
                             .includes(:tags)
                             .preload(:invite, owner: [{ invite: [:sender] }])
                             .order("startups.#{sort_column}" + " " + sort_direction)

    @favorite_list = List.includes(:startups).favorite_list(current_user)
    @startup_tags = StartupTag.startup_tags(@startups.pluck(:id), current_user.team_mate_ids)
    @back_link = tags_url(search: params[:tags_search], page: params[:tags_page])
  end

  private

  def find_tag
    @tag = Tag.find_by(id: params[:id])
  end

  def set_download_startup_ids
    session[:download_startup_ids] =
      @startups.any? ?  @startups.map(&:id) : []
      # @startups.any? ?  @startups.per(@startups.total_count).page(1).map(&:id) : []
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_empty_tags.html.erb
<div class="empty_block empty_block_pt">
  <i class="icon icon_listings"></i>
  <h1 class="empty_title">Add Tags to Startups</h1>
  <p class="empty_text">Use tags to manage startups</p>
</div>

app/views/tags/_index.html.erb
<div class="detail_item_title <%= params[:action] == 'profile' ? '' : 'tags__lighten' %>">
  KEYWORD TAGS
  <a href="#" class="js__show__tags">
    <span>+ Add tags</span>
    <span>&times; Cancel</span>
  </a>
</div>
<div class="detail_item_content">
  <input type="text" name="tags" placeholder="Add tags, separate with coma" class="tags__block--input"/>
  <div class="tags__block--tags clearfix"></div>
</div>

app/views/tags/_nothing_found.html.erb
<div class="empty_block empty_tags_search">
  <i class="icon icon_search"></i>
  <h1 class="empty_title">Nothing Found</h1>
  <p class="empty_text">No results match your search terms. Try another query.</p>
</div>

app/views/tags/_tags.html.erb
<% @tags.each do |tag| %>
  <%= link_to tag.title, tag_path(tag, tags_search: @search, tags_page: params[:page]), class: "btn btn_bordered_const" %>
<% end %>
<br/>
<%= paginate @tags %>

app/views/tags/_tags_holder.html.erb
<span class="dropdown-menu dropdown-menu_tags" id="menu4">
  <span class="dropdown-menu_title">Tags</span>
  <span class="tags_items">
    <% tags.each do |tag| %>
      <%= link_to tag.title, tag_path(tag), class: 'tag' %>
    <% end %>
  </span>
</span>

app/views/tags/_tags_search.html.erb
<%= form_for tags_url, method: :get do |f| %>
  <div class="inner_search_wrap">
    <div class="inner_search<%= ' active_search' if @search %>">
      <div class="field_search_holder">
        <%= text_field_tag :search, @search, class:'form-control inner_field_search', placeholder: 'Search for a keyword' %>
        <%= link_to 'X', tags_url, class: 'clear_field' if @search %>
      </div>
      <i class="icon icon_search"></i>
      <input type="submit" class='btn btn_add' value="Search">
    </div>
  </div>
<% end %>

app/views/tags/_top_bar_tag.html.erb
<div class="top_panel clearfix">
  <div class="top_panel_text_holder pull-left">
    <div class="top_panel_text">
      <%= tag.title %>
    </div>
  </div>
  <%= link_to @back_link || tags_path, class: "close_panel" do %>
    <i class="icon icon_close"></i>
  <% end %>
</div>

app/views/tags/create.js.erb
startup_holder = $("#startup_<%= @startup.id %>");
tags_holder = startup_holder.find("span.tags_items");
count_holder = startup_holder.find("span.tags");
tags_container = $("#tags_container_for_startup_<%= @startup.id %>");

count_holder.html("<%= j render partial: 'tags/tags_count', locals: { tag_count: @tags_collection.count } %>");

<% if @tags_collection.count == 1 %>
  tags_container.html("<%= j render partial: 'tags/tags_holder', locals: { startup: @startup } %>");
<% else %>
  tags_holder.html("<%= j render partial: '/tags/list_tag', collection: @tags_collection %>");
<% end %>

app/views/tags/index.html.erb
<% if @tags.any? || @search %>
  <div class="head_content head_content_padd hidden-xs">
    <h1 class="h1_title">Keyword Tags</h1>
    <div class="subtitle">Below are the list of keywords added to startup profiles.</div>
  </div>

  <div class="light_block">
    <div class="light_block_body">
      <%= render 'tags_search' %>
      <div class="tags_holder">
        <% if @tags.any? %>
          <%= render 'tags' %>
        <% else %>
          <%= render 'nothing_found' %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'empty_tags' %>
<% end %>

<div id="startups-index"></div>

app/views/tags/index.js.erb
// $("#startups-index").empty();
// $(".heading").remove();
// $("#top_bar_tag").remove();
// $(".box_row").empty();
// $("<%# j( render 'tags', tag: @tags ) %>").prependTo("#startups-index");

$('.tags_holder').html("<%= j render('tags') %>");

app/views/tags/new.js.erb
el = $(".new_tag_form")
el.html("<%= j render 'new' %>")

app/views/tags/show.html.erb
<%= render '/startups/filter_startups' %>
<div class="list_holder">
  <h2 class="mobile_title visible-xs">All Startups</h2>
  <div class="boxer hovered styled_list">
    <div class="box_row clearfix box_head hidden-xs">
      <%= render 'startups/header' %>
    </div>
    <div id="startups-index">
      <%= render partial: '/startups/startup', collection: @startups %>
    </div>
  </div>
</div>

app/views/tags/show.js.erb
$("#startups-index").html("<%= j( render partial: '/startups/startup', collection: @startups) %>");
$.controlMethods.removePlaceholder();